### ISSUE TITLE
Extract CPE data

### ISSUE THREAD

**Issue by decke** [yurivict/freebsd-portsdb#1]
Would it be possible to also extract and store CPE_STR (set in Uses/cpe.mk) if it was set by a port?

Currently I am also extracting various variables from our full portstree and store it in sqlite in [chkcpe](https://github.com/decke/chkcpe). So that is partially similar to portsdb but written in PHP now (early versions were written in Shell actually). Extracting all the data via "make -V.." from the portstree is an expensive operation so I did some optimizations and using GNU parallel has given the best results.

https://github.com/decke/chkcpe/blob/07b5c25bfaa8bbd54d4a590f359f02def18faf0f/src/Runner.php#L140

Another probably interesting detail is that I run chkcpe as a GitHub Action on the Ubuntu workers because FreeBSD is not supported. That actually means I checkout the FreeBSD portstree on Ubuntu and walk the portstree using bmake which is absolutely not supported by our portstree but works good enough if some environment variables and some Mk seeds are provided.

https://github.com/decke/chkcpe/blob/07b5c25bfaa8bbd54d4a590f359f02def18faf0f/.github/workflows/build.yml#L49
https://github.com/decke/chkcpe/tree/main/share/mk

**Comment by yurivict** [comment]
I'll add this field, thanks.

**Comment by yurivict** [comment]
The field Port.CPE_STR was added.
It will be included in the next release.

**Comment by decke** [comment]
Thanks a lot yuri!
