### ISSUE TITLE
Please honour TMPDIR

### ISSUE THREAD

**Issue by Jamie-Landeg-Jones** [yurivict/freebsd-portsdb#2]
I've just installed this port (I read about it in the FreeBSD quarterly status report). It looks like just what I'm after!

A few notes / suggestions so far:

Please can you honour the TMPDIR setting with mkdir.

man mkdir:
"If the -t prefix option is given, mktemp will generate a template string based on the prefix and the TMPDIR environment variable if set.  The default location if TMPDIR is not set is /tmp.  Care should be taken to ensure that it is appropriate to use an environment variable potentially supplied by the user."

e.g.:

SQL_FILE=$(mktemp /tmp/ports.sql.XXXXXX)   -->   SQL_FILE=$(mktemp -t ports.sql)

In addition, you can use mktemp -d to create a temporary directory, rather than creating a file, deleting it, and making a directory in its place. (Avoids a very unlikely but potential race-condition hack!)

Also, in includes.sh:

if [ $(echo $(which $dep) | wc -w | sed -e 's| ||g') = 0 ]; then

can be replaced with:

if ! which -s "$dep"; then

Cheers!

**Comment by yurivict** [comment]
Hi Jamie,

Thanks for your suggestions!

Yuri

**Comment by Jamie-Landeg-Jones** [comment]
Hi! Thanks for that, and the quick response!

Cheers.

**Comment by Jamie-Landeg-Jones** [comment]
Hi! Thanks for doing that, and for your quick response!

I just realised you're the same guy I sent an update for the unicode-emojis port. I'm not stalking you, honest!

**Comment by yurivict** [comment]
:-)
